# Delay between each ping update
# can be [seconds, minutes, hours]
delay: 10 seconds
# Servers are configured here
servers:
  lobby:
    players: false
    favicon: false
    motd: true
    version: false
    mods: true
  factions:
    players: true
    favicon: true
    motd: true
    version: true
    mods: true